###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /foxlara-app
        volumes:
            - '.:/foxlara-app'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=foxlara
        ports:
            - '5004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /foxlara-app
        volumes:
            - '.:/foxlara-app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '5000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /foxlara-app
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
            XDEBUG_MODE: "coverage"
        volumes:
            - '.:/foxlara-app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini'

